language: node_js

node_js:
  - '0.10'
  - '0.12'

script: npm run $ACTION

before_script:
  - psql -c 'create database "azul_test";' -U postgres
  - mysql -e 'create database `azul_test`;'

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls

env:
  - ACTION=test-travis PG_USER=postgres MYSQL_USER=travis
  - ACTION=docs

matrix:
  exclude:
    - env: ACTION=docs
  include:
    - env: ACTION=docs
      node_js: '0.12'

fast_finish: true

sudo: false
